  <!--#if expr="$REMOTE_ADDR = /139\.19\..*\..*/" -->
      <!-- CORRECT HERE:                                                       -->
      <!-- this is visible only from inside the institute.                     --> 
      <!-- It's convenient for everyone in the institute.                      -->
      <!-- That way spammers can not harvest your email address                -->

      <!-- <a href="mailto:unixlogin@mpi-inf.mpg.de">unixlogin@mpi-inf.mpg.de</a><br />-->

  <!--#else -->
      <!-- CORRECT HERE: Your personal URL can be found on the people page     -->
      <!-- How to find the unique URL for your email address:                  -->
      <!-- 1. Open in your browser:                                            --> 
      <!--          http://people.mpi-inf.mpg.de/people/index.html             -->
      <!-- 2. Find your name entry on that page                                -->
      <!-- 3. Copy the URL from the Email column that reads "Retrieve email"   --> 
      <!--    Tip: - Right click on the linked text "Retrieve email"           -->
      <!--         - and "Copy Link Location"                                  -->
      <!-- 4. Paste/Put this copied URL into the href-anchor tag below         -->

      <a href="https://domino.mpi-inf.mpg.de/intranet/mpii/people.nsf/email!ReadForm&UID=23109&Name=Maghsoudlou%2C%20Aniss&">Get my email address via email</a><br />

  <!--#endif -->
