<!-- include file: menu.inc; start -->
<ul class="nav nav-stacked">
  <li><a href="#contact" accesskey="c" title="Contact" id="hp-contact"><span class="ak">C</span>ontact</a></li>
  <li><a href="#research" accesskey="r" title="Research Interests" id="hp-research"><span class="ak">R</span>esearch Interests</a></li>
  <li><a href="#publications" accesskey="p" title="Publications of Firstname Lastname" id="hp-publications"><span class="ak">P</span>ublications</a></li>
  <li><a href="#teaching" accesskey="t" title="Teaching of Firstname Lastname" id="hp-teaching"><span class="ak">T</span>eaching</a></li>
  <li><a href="#positions" accesskey="o" title="Positions of Firstname Lastname" id="hp-positions">Recent P<span class="ak">o</span>sitions</a></li>
  <li><a href="#education" accesskey="e" title="Education of Firstname Lastname" id="hp-education"><span class="ak">E</span>ducation</a></li>
  <li><a href="#links" accesskey="l" title="Private Stuff of Firstname Lastname"><span class="ak">L</span>inks</a></li>
  <li><a href="#private" accesskey="a" title="Private Stuff of Firstname Lastname" id="hp-private"><span class="ak">P</span>rivate</a></li>
  <!-- CHANGE HERE: Put your own menu items here. They can also point to different web pages. --> 
</ul>
<!-- include file: menu.inc; end -->
